/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirQualityRecord } from "./AirQualityRecord";
export * as factories from "./factories";
export { AirQualityRecord__factory } from "./factories/AirQualityRecord__factory";
